### ISSUE TITLE
Got 3 errors when you try to refresh the login page

### ISSUE THREAD

**Issue by ahmadrahmat** [primefaces/sakai-react#43]
I got these errors when i try to refresh the login page. can you guys help me?

![Screenshot 2023-03-23 044941](https://user-images.githubusercontent.com/26665811/227034769-6e40a45a-229f-45b3-95cd-989c97ffab87.png)
![Screenshot 2023-03-23 044926](https://user-images.githubusercontent.com/26665811/227034775-5fea0da7-8da8-4cc1-926c-07def7dfa82a.png)
![Screenshot 2023-03-23 044905](https://user-images.githubusercontent.com/26665811/227034779-420d3d2d-3a1d-4048-8d24-bf596ed2f097.png)

**Comment by UrielMartinez21** [comment]
Igual a mi me parece esos errores, ¿Aun no se soluciona?

**Comment by gesangseto** [comment]
any update?

**Comment by ahmadrahmat** [comment]
> any update?

still no update yet

**Comment by gesangseto** [comment]
The error will disappear if you remove the button, because the problem is with the button

try to change 
``
<Button label="Sign In" className="w-full p-3 text-xl" onClick={() => router.push('/')}></Button>
``
with your button from html/react, eg:
``
<button className="w-full p-3 text-xl" style={{ borderRadius: 10, backgroundColor: 'blue', color: 'white', borderColor: 'blue' }}>Sign In</button>
``

**Comment by gucal** [comment]
It has been fixed:
https://github.com/primefaces/sakai-react/commit/a5040fe6ec163f4039d01858c291268ab1ce5fe3
